<template>
    <Head><title>Движения материалов</title></Head>
    <div class="mi-page"><div class="content-header"><div class="container-fluid"><h5 class="m-0">Движения материалов</h5></div></div>
    <div class="content"><div class="container-fluid"><div class="card"><div class="card-body"><form class="row mb-3" @submit.prevent="filter"><div class="col-md-2 mb-2"><input v-model="form.from" type="date" class="form-control"></div><div class="col-md-2 mb-2"><input v-model="form.to" type="date" class="form-control"></div><div class="col-md-3 mb-2"><select v-model="form.nomenclature_id" class="form-control"><option value="">Материал</option><option v-for="item in materials" :value="item.id">{{ item.name }}</option></select></div><div class="col-md-2 mb-2"><select v-model="form.type" class="form-control"><option value="">Тип</option><option v-for="(label, value) in types" :value="value">{{ label }}</option></select></div><div class="col-md-2 mb-2"><select v-model="form.direction" class="form-control"><option value="">Направление</option><option v-for="(label, value) in directions" :value="value">{{ label }}</option></select></div><div class="col-md-1"><button class="btn btn-primary">Найти</button></div></form>
        <div class="table-responsive mi-table-wrap"><table class="table table-bordered mi-mobile-table"><thead><tr><th>Дата</th><th>Материал</th><th>Тип</th><th>Приход</th><th>Расход</th><th>Основание</th><th>Комментарий</th><th>Пользователь</th></tr></thead><tbody><tr v-for="movement in movements.data"><td data-label="Дата">{{ movement.occurred_at }}</td><td data-label="Материал">{{ movement.nomenclature }}</td><td data-label="Тип">{{ movement.type_label }}</td><td data-label="Приход">{{ movement.direction === 'in' ? movement.quantity + ' ' + movement.unit : '' }}</td><td data-label="Расход">{{ movement.direction === 'out' ? movement.quantity + ' ' + movement.unit : '' }}</td><td data-label="Основание">{{ movement.source }}</td><td data-label="Комментарий">{{ movement.comment }}</td><td data-label="Пользователь">{{ movement.created_by }}</td></tr></tbody></table></div><pagination v-if="movements.links.length > 3" :links="movements.links" />
    </div></div></div></div></div>
</template>
<script>
import {Head} from '@inertiajs/inertia-vue3'; import Pagination from '../../Shared/Pagination.vue';
export default {components: {Head, Pagination}, props: ['movements', 'filters', 'materials', 'types', 'directions'], data() { return {form: {...this.filters}} }, methods: {filter() { this.$inertia.get(route('material-inventory.movements'), this.form, {preserveState: true}) }}};
</script>
