export const CASH_TRANSACTION_STATUS_COMPLETED = 1;
export const CASH_TRANSACTION_STATUS_CANCEL = 2;

export const CASH_TRANSACTION_STATUS_LABELS = {
    [CASH_TRANSACTION_STATUS_COMPLETED]: 'Проведен',
    [CASH_TRANSACTION_STATUS_CANCEL]: 'Отменен',
}
